project:
  output-dir: docs
  render:
    - assets2023_vscode.qmd
editor:
  render-on-save: true
  mode: visual
format:
  acm-pdf:
    output-file: index.pdf
    include-in-header:
      text: |
        % !TEX program = xelatex
    # use keep-tex to cause quarto to generate a .tex file
    # which you can eventually use with TAPS
    keep-tex: true
  acm-html:
    output-file: index.html

bibliography: bibliography.bib

title: "Coding Non-Visually in Visual Studio Code: Collaboration Towards Accessible Development Environment for Blind Programmers"

# if short-title is defined, then it's used
short-title: "VSCode_A11y"

author:
  - name: JooYoung Seo
    email: jseo1005@illinois.edu
    orcid: 0000-0002-4064-6012
    affiliation:
      name: School of Information Sciences, University of Illinois at Urbana-Champaign
      address: 614 E Daniel St
      city: Champaign
      state: Illinois
      country: USA
      postal-code: 61820
  - name: Megan Rogge
    email: megrogge@gmail.com
    affiliation:
      name: Microsoft
      address: 1 Microsoft Way
      city: Redmond
      state: Washington
      country: USA
      postal-code: 98052

# acm-specific metadata
acm-metadata:
  # comment this out to make submission anonymous
  # anonymous: true
  
  # comment this out to build a draft version
  # final: true

  # comment this out to specify detailed document options
  acmart-options: manuscript,review

  # acm preamble information
  copyright-year: 2018
  acm-year: 2018
  copyright: acmcopyright
  doi: XXXXXXX.XXXXXXX
  conference-acronym: "ASSETS"
  conference-name: |
    The 25th International ACM SIGACCESS Conference on Computers and Accessibility
  
  conference-date: October 22--25, 2023
  conference-location: New York, NY
  price: "15.00"
  isbn: 978-1-4503-XXXX-X/18/06

  # if present, replaces the list of authors in the page header.
  shortauthors: Seo and Rogge


  # The code below is generated by the tool at http://dl.acm.org/ccs.cfm.
  # Please copy and paste the code instead of the example below.
  ccs: |
    \begin{CCSXML}
    <ccs2012>
      <concept>
          <concept_id>10003120.10011738.10011774</concept_id>
          <concept_desc>Human-centered computing~Accessibility design and evaluation methods</concept_desc>
          <concept_significance>500</concept_significance>
          </concept>
    </ccs2012>
    \end{CCSXML}

    \ccsdesc[500]{Human-centered computing~Accessibility design and evaluation methods}

  keywords:
    - nonvisual programming
    - accessibility
    - integrated development environment
    - visual studio code
  
  # if uncommented, this produces a teaser figure
  # 
  # teaser:
  #   image: sampleteaser
  #   caption: figure caption
  #   description: teaser description    

abstract: |
  This paper delineates a fruitful collaboration between blind and sighted developers, aiming to augment the accessibility of Visual Studio Code (VSCode). Our shared journey is portrayed through examples drawn from our interaction with GitHub issues, pull requests, review processes, and insider's releases, each contributing to an improved VSCode experience for blind developers. One key milestone of our co-design process is the establishment of an accessible terminal buffer, a significant enhancement for blind developers using VSCode. Other innovative outcomes include Git Diff audio cues, adaptable verbosity settings, intuitive help menus, and a targeted accessibility testing initiative. These tailored improvements not only uplift the accessibility standards of VSCode but also provide a valuable blueprint for open-source developers at large. Through our shared dedication to promoting inclusivity in software development, we aim for the strategies and successes shared in this paper to inspire and guide the open-source community towards crafting more accessible software environments. Accessible HTML version of this paper is available at [https://jooyoungseo.github.io/assets2023_vscode/](https://jooyoungseo.github.io/assets2023_vscode/).
