project:
  output-dir: docs
  render:
    - assets2023_vscode.qmd
editor:
  render-on-save: true
  mode: visual
format:
  acm-pdf:
    output-file: index.pdf
    include-in-header:
      text: |
        % !TEX program = xelatex
    # use keep-tex to cause quarto to generate a .tex file
    # which you can eventually use with TAPS
    keep-tex: true
  acm-html:
    output-file: index.html

bibliography: bibliography.bib

title: "Coding Non-visually in Visual Studio Code: Collaboration Towards Accessible Development Environment for Blind Programmers"

# if short-title is defined, then it's used
short-title: "VSCode"

author:
  - name: JooYoung Seo
    email: jseo1005@illinois.edu
    orcid: 0000-0002-4064-6012
    affiliation:
      name: School of Information Sciences, University of Illinois at Urbana-Champaign
      address: 614 E Daniel St
      city: Champaign
      state: Illinois
      country: USA
      postal-code: 61820
  - name: Megan Rogge
    email: megrogge@gmail.com
    affiliation:
      name: Microsoft
      address: 1 Microsoft Way
      city: Redmond
      state: Washington
      country: USA
      postal-code: 98052

# acm-specific metadata
acm-metadata:
  # comment this out to make submission anonymous
  # anonymous: true
  
  # comment this out to build a draft version
  # final: true

  # comment this out to specify detailed document options
  acmart-options: manuscript,review

  # acm preamble information
  copyright-year: 2018
  acm-year: 2018
  copyright: acmcopyright
  doi: XXXXXXX.XXXXXXX
  conference-acronym: "Conference acronym 'XX"
  conference-name: |
    Make sure to enter the correct
    conference title from your rights confirmation emai
  conference-date: June 03--05, 2018
  conference-location: Woodstock, NY
  price: "15.00"
  isbn: 978-1-4503-XXXX-X/18/06

  # if present, replaces the list of authors in the page header.
  shortauthors: Seo and Rogge


  # The code below is generated by the tool at http://dl.acm.org/ccs.cfm.
  # Please copy and paste the code instead of the example below.
  ccs: |
    \begin{CCSXML}
    <ccs2012>
     <concept>
      <concept_id>10010520.10010553.10010562</concept_id>
      <concept_desc>Computer systems organization~Embedded systems</concept_desc>
      <concept_significance>500</concept_significance>
     </concept>
     <concept>
      <concept_id>10010520.10010575.10010755</concept_id>
      <concept_desc>Computer systems organization~Redundancy</concept_desc>
      <concept_significance>300</concept_significance>
     </concept>
     <concept>
      <concept_id>10010520.10010553.10010554</concept_id>
      <concept_desc>Computer systems organization~Robotics</concept_desc>
      <concept_significance>100</concept_significance>
     </concept>
     <concept>
      <concept_id>10003033.10003083.10003095</concept_id>
      <concept_desc>Networks~Network reliability</concept_desc>
      <concept_significance>100</concept_significance>
     </concept>
    </ccs2012>
    \end{CCSXML}
    
    \ccsdesc[500]{Computer systems organization~Embedded systems}
    \ccsdesc[300]{Computer systems organization~Redundancy}
    \ccsdesc{Computer systems organization~Robotics}
    \ccsdesc[100]{Networks~Network reliability}

  keywords:
    - nonvisual programming
    - accessibility
    - integrated development environment
    - visual studio code
  
  # if uncommented, this produces a teaser figure
  # 
  # teaser:
  #   image: sampleteaser
  #   caption: figure caption
  #   description: teaser description    

abstract: |
  In this paper, we will showcase a few examples of how blind and sighted developers have been working together to make Visual Studio Code more accessible. Through our collaboration, which is evident in the GitHub issues, pull requests, review process, and insider's releases we've created together over the past few months, we hope to help other open source developers use these methods to create more accessible development environments.
